import { test, expect } from "@playwright/test";

test("organizers search categories, choose three, and keep selections after validation", async ({ page }, info) => {
  await page.addInitScript(() => { window.eventSubmissionError = "Please review your event details."; });
  await page.goto("/event-form");
  const trigger = page.getByRole("button", { name: "Choose happening categories", exact: true });
  const search = page.getByLabel("Search happening categories", { exact: true });
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await expect(page.getByRole("button", { name: "Remove Live Music", exact: true })).toBeVisible();
  await trigger.click();
  await expect(page.getByRole("checkbox", { name: "Live Music", exact: true })).toBeChecked();
  await search.fill("Family");
  await page.getByRole("checkbox", { name: "Family Friendly", exact: true }).check();
  await search.fill("Food");
  await page.getByRole("checkbox", { name: "Food & Drink", exact: true }).check();
  await search.fill("Outdoor");
  await expect(page.getByRole("checkbox", { name: "Outdoor", exact: true })).toBeDisabled();
  await expect(page.getByText("3/3 selected", { exact: true })).toBeVisible();
  await search.press("Escape");
  await expect(trigger).toBeFocused();
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("button", { name: "Remove Family Friendly", exact: true }).click();
  await trigger.click();
  await search.fill("Outdoor");
  await page.getByRole("checkbox", { name: "Outdoor", exact: true }).check();
  await search.press("Escape");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Please review your event details.");
  expect(await page.evaluate(() => window.eventSubmissions[0].categoryIds)).toEqual(["event-Live Music", "event-Food & Drink", "event-Outdoor"]);
  await expect(page.getByRole("button", { name: "Remove Live Music", exact: true })).toBeVisible();
  await expect(page.getByText("3/3 selected", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await trigger.scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/event-categories-${info.project.name}.png` });
});

test("tags offer a filtered checkbox list and explicit custom tag additions", async ({ page }, info) => {
  await page.goto("/event-form-edit");
  const group = page.getByRole("group", { name: "Tags", exact: true });
  const trigger = page.getByRole("button", { name: "Choose tags", exact: true });
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await trigger.click();
  await expect(group.getByRole("checkbox", { name: "Event Category: Community", exact: true })).toHaveCount(0);
  await group.getByLabel("Search tags", { exact: true }).fill("free");
  await group.getByRole("checkbox", { name: "Free Admission", exact: true }).check();
  await expect(group.getByRole("checkbox")).toHaveCount(1);
  await group.getByLabel("Search tags", { exact: true }).fill("Picnic");
  await expect(group.getByText("No matches found. Try another search.", { exact: true })).toBeVisible();
  await group.getByRole("button", { name: "Add “Picnic”", exact: true }).click();
  await expect(group.getByRole("checkbox", { name: "Picnic", exact: true })).toBeChecked();
  await group.getByLabel("Search tags", { exact: true }).fill("Family");
  await group.getByRole("checkbox", { name: "Family", exact: true }).check();
  await group.getByLabel("Search tags", { exact: true }).press("Escape");
  await expect(trigger).toBeFocused();
  await trigger.press("Enter");
  await group.getByLabel("Search tags", { exact: true }).fill("free");
  await expect(group.getByRole("checkbox", { name: "Free Admission", exact: true })).toBeChecked();
  await group.getByLabel("Search tags", { exact: true }).press("Escape");
  await page.getByRole("button", { name: "Save Changes", exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.eventSubmissions?.[0]?.tags)).toBe("Free Admission, Picnic, Family");
  await group.scrollIntoViewIfNeeded();
  await page.screenshot({ path: `test-results/event-tags-${info.project.name}.png` });
});
